"""HLS C++ codegen backend for the GNN generator (A6).

Consumes a `GNNModelGraph` and emits synthesizable C++ that instantiates the
`src/mp_template.h` primitives, plus a Vitis HLS project tcl. This is the
backend-template half of the hls4ml port: in upstream hls4ml the equivalent
lives under `hls4ml/backends/<backend>/passes/` as a layer-template writer.

Supported in the auto-chained path: GCN and GraphSAGE layers (single-linear
update). GIN and EGNN have dedicated hand-written tops (src/mp_layers.cpp,
src/egnn_layer.cpp); the generator references those rather than re-emitting
their multi-layer MLPs, and this is called out explicitly if requested.
"""

from __future__ import annotations

import os
from typing import List

from .ir import Aggregation, GNNLayer, GNNModelGraph

_AUTO_KINDS = {"gcn", "sage"}


def emit_accelerator(graph: GNNModelGraph, out_dir: str) -> List[str]:
    """Emit generated_model.{h,cpp} and run_generated.tcl into out_dir.

    Returns the list of written file paths.
    """
    for ly in graph.layers:
        if ly.kind not in _AUTO_KINDS:
            raise NotImplementedError(
                f"layer '{ly.name}' kind '{ly.kind}' is not in the auto-chained "
                f"path ({sorted(_AUTO_KINDS)}). Use the dedicated top: "
                f"gin_layer/sage_layer (src/mp_layers.cpp) or "
                f"egnn_layer (src/egnn_layer.cpp)."
            )

    os.makedirs(out_dir, exist_ok=True)
    header = _emit_header(graph)
    source = _emit_source(graph)
    tcl = _emit_tcl(graph)

    paths = []
    for fname, text in (
        ("generated_model.h", header),
        ("generated_model.cpp", source),
        ("run_generated.tcl", tcl),
    ):
        p = os.path.join(out_dir, fname)
        with open(p, "w", encoding="utf-8") as f:
            f.write(text)
        paths.append(p)
    return paths


def _wname(i: int) -> str:
    return f"l{i}_W"


def _bname(i: int) -> str:
    return f"l{i}_b"


def _emit_header(graph: GNNModelGraph) -> str:
    L = graph.layers
    in0 = L[0].in_dim
    outL = L[-1].out_dim
    lines = [
        "#ifndef GENERATED_MODEL_H",
        "#define GENERATED_MODEL_H",
        "",
        '#include "mp_template.h"',
        "",
        "// Auto-generated by hls4ml_gnn.codegen -- do not edit by hand.",
        f"#define GEN_MAX_NODES {graph.max_nodes}",
        f"#define GEN_MAX_EDGES {graph.max_edges}",
        f"#define GEN_F_IN  {in0}",
        f"#define GEN_F_OUT {outL}",
        "",
        "struct gen_weights_t {",
    ]
    for i, ly in enumerate(L):
        lines.append(f"    weight_t {_wname(i)}[{ly.in_dim}][{ly.out_dim}];")
        lines.append(f"    weight_t {_bname(i)}[{ly.out_dim}];")
    lines += [
        "};",
        "",
        "void generated_model(",
        "    const gen_weights_t &Wt,",
        "    const data_t   X[GEN_MAX_NODES][GEN_F_IN],",
        "    const idx_t    row_ptr[GEN_MAX_NODES + 1],",
        "    const idx_t    col_idx[GEN_MAX_EDGES],",
        "    idx_t          num_nodes,",
        "    data_t         Y[GEN_MAX_NODES][GEN_F_OUT]);",
        "",
        "#endif // GENERATED_MODEL_H",
        "",
    ]
    return "\n".join(lines)


def _emit_source(graph: GNNModelGraph) -> str:
    L = graph.layers
    n = graph.max_nodes
    e = graph.max_edges
    lines = [
        '#include "generated_model.h"',
        "",
        "void generated_model(",
        "    const gen_weights_t &Wt,",
        "    const data_t   X[GEN_MAX_NODES][GEN_F_IN],",
        "    const idx_t    row_ptr[GEN_MAX_NODES + 1],",
        "    const idx_t    col_idx[GEN_MAX_EDGES],",
        "    idx_t          num_nodes,",
        "    data_t         Y[GEN_MAX_NODES][GEN_F_OUT])",
        "{",
    ]
    # Declare per-layer combine and aggregate buffers.
    for i, ly in enumerate(L):
        lines.append(f"    static data_t comb{i}[{n}][{ly.out_dim}];")
        lines.append(f"    #pragma HLS ARRAY_PARTITION variable=comb{i} complete dim=2")
        # aggregate output buffer; last layer writes Y directly
        if i != len(L) - 1:
            lines.append(f"    static data_t agg{i}[{n}][{ly.out_dim}];")
            lines.append(f"    #pragma HLS ARRAY_PARTITION variable=agg{i} complete dim=2")
    lines.append("")

    prev = "X"
    for i, ly in enumerate(L):
        norm = "true" if ly.normalize else "false"
        agg_enum = ly.aggregation.to_cpp_enum()
        out_buf = "Y" if i == len(L) - 1 else f"agg{i}"
        # GCNConv ordering: combine (linear) then aggregate.
        lines.append(f"    // layer {i}: {ly.kind} {ly.in_dim}->{ly.out_dim} "
                     f"(aggr={ly.aggregation.value}, norm={ly.normalize})")
        lines.append(
            f"    mp_linear<{n}, {ly.in_dim}, {ly.out_dim}>"
            f"({prev}, Wt.{_wname(i)}, Wt.{_bname(i)}, num_nodes, comb{i});"
        )
        lines.append(
            f"    mp_aggregate<{n}, {e}, {ly.out_dim}, {agg_enum}, {norm}>"
            f"(comb{i}, row_ptr, col_idx, num_nodes, {out_buf});"
        )
        lines.append("")
        prev = out_buf

    lines += ["}", ""]
    return "\n".join(lines)


def _emit_tcl(graph: GNNModelGraph) -> str:
    return "\n".join(
        [
            "# Auto-generated Vitis HLS project for the codegen'd GNN model.",
            "#   rm -rf gen_proj && vitis_hls -f run_generated.tcl",
            "open_project -reset gen_proj",
            "set_top generated_model",
            f'add_files generated_model.cpp -cflags "-I../src -I. '
            f'-DGNN_PRECISION_PROFILE={graph.precision_profile}"',
            "open_solution -reset sol1 -flow_target vivado",
            "set_part {xczu3eg-sbva484-1-e}",
            "create_clock -period 3.33 -name default",
            "csynth_design",
            "exit",
            "",
        ]
    )
