"""Derive energy numbers from power + cosim JSON (no hand-typed doc values)."""

import argparse
import json
from pathlib import Path

OE_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = OE_ROOT / "characterization" / "out" / "phase2"
DOC = OE_ROOT / "docs" / "dynamic_graph_cost_model.md"


def _load(name):
    path = OUT_DIR / name
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def microjoules(dynamic_w, cycles, fmax_mhz):
    if dynamic_w is None or cycles is None or not fmax_mhz:
        return None
    seconds = float(cycles) / (fmax_mhz * 1e6)
    return round(dynamic_w * seconds * 1e6, 4)


def build_summary():
    csynth = _load("csynth_scatter.json") or {}
    fmax = csynth.get("estimated_fmax_mhz") or 404.4
    stream = _load("cosim_stream.json") or {}
    graph = _load("cosim_graph_load.json") or {}
    p_scatter = _load("power_scatter.json") or {}
    p_graph = _load("power_graph_load.json") or {}

    cpt = stream.get("per_transaction_cycles") or stream.get("latency_cycles")
    uj_decision = microjoules(p_scatter.get("dynamic_w"), cpt, fmax)

    session_cycles = graph.get("per_session_cycles") or graph.get("latency_cycles")
    uj_session = microjoules(p_graph.get("dynamic_w"), session_cycles, fmax)

    return {
        "fmax_mhz": fmax,
        "cycles_per_completion": cpt,
        "uj_per_decision": uj_decision,
        "session_load_cycles": session_cycles,
        "uj_per_session_load": uj_session,
        "power_scatter_status": p_scatter.get("status"),
        "power_graph_load_status": p_graph.get("status"),
        "software_anchor_ms": {"langgraph_min": 1.7, "langgraph_max": 3.4},
    }


def patch_doc(summary):
    if not DOC.exists():
        return
    text = DOC.read_text(encoding="utf-8")
    marker = "## Energy (generated"
    block = (
        "## Energy (generated by characterization/energy_calc.py)\n\n"
        "- Fmax (csynth): **{fmax_mhz} MHz**\n"
        "- Scatter: **{cycles_per_completion} cycles/completion**"
        " -> **{uj_per_decision} uJ/decision** (needs dynamic_w from power JSON)\n"
        "- Session load: **{session_load_cycles} cycles/session**"
        " -> **{uj_per_session_load} uJ/session** (needs dynamic_w from power JSON)\n"
        "- Software anchor (LangGraph setup): **1.7 to 3.4 ms** per session\n"
    ).format(**summary)

    if marker in text:
        head = text.split(marker)[0]
        tail_parts = text.split(marker, 1)[1].split("\n## ", 1)
        tail = ""
        if len(tail_parts) > 1:
            tail = "\n## " + tail_parts[1]
        text = head.rstrip() + "\n\n" + block + tail
    else:
        old = "## Energy (first order; scatter csynth measured, power report pending)"
        if old in text:
            text = text.replace(old, block.rstrip())
        else:
            text = text.rstrip() + "\n\n" + block

    DOC.write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-doc", action="store_true")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUT_DIR / "energy_summary.json",
    )
    args = parser.parse_args()

    summary = build_summary()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))
    if args.write_doc:
        patch_doc(summary)
        print("Updated {0}".format(DOC))


if __name__ == "__main__":
    main()
